### PR TITLE
Fix and issue causing Portable AC to fail

### PR DESCRIPTION
**Pull request by stevehof**
There are 2 fixes (2 commits) in this PR as there are 2 issues in #39 that are linked but different. It's unknown if either resolve the original posters issue.

### Fix in 2447ff1c79e17b470826b8d5ce8d24a7d5d09f8f

This should resolve issues attached to this [comment ](https://github.com/nemesa/ha-tcl-home-unofficial-integration/issues/39#issuecomment-3368154248) in #39 

There would be an Exception that was caught while getting the capabilities in `device.py` causing any TCL devices with an empty fan_speed_mapping map in the aws data  dump to fail to load.

The data from AWS:
image

The issue was that parse_fan_speed_mapping in `device_rn_probe.py` would return None (and was typed to) but the locations that used `fan_speed_mapping` couldn't handle the None.

For example in device_features.py:375 it treats `rn_probe_data.get("fan_speed_mapping", [])` as always a List and never handles a None. Since an empty List is essentially `None` with respect to this context, just returning an empty list is the smallest change that also makes sense.

The Exception that killed it for most people was on line device_features.py:377 where it would try `<str> in <None>`

Fix in ### 494a0bcc7bb42ff6956bd9b77702c86951ecea72:

This resolves this [comment ](https://github.com/nemesa/ha-tcl-home-unofficial-integration/issues/39#issuecomment-3262008141) specifically ` for climate: getPortableWind4ValueSeed() missing 1 required positional argument: 'has_auto_mode'`

This issue was introduced in a9593256d8548e0720eaf95576845e4c4ee2db7d when climate.py didn't specifiy the 2nd param `has_auto_mode`. I've added a default to has_auto_mode in getPortableWind4ValueSeed because i cannot test or confirm what has_auto_mode should be in climate.py. 

Testing:

I tested that the `NoneType` issue is gone, and that the integration loads and continues to work.

### CODE REVIEW

**Comment by nemesa** [comment]
Thanks for to contribution, will try to review and pull this the in a few days!

**Review by nemesa — APPROVED** [review]
LGTM

**Comment by nemesa** [comment]
Thanks @stevehof very nice PR!
Well explaind and small enough changes.
Will incude in the next release, thanks a lot for your time and contribution!
